src/Entity/Meme.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use App\Repository\MemeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\String\Slugger\SluggerInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=MemeRepository::class)
 * @ApiResource()
 */
class Meme
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     *
     * @Groups({"meme:list", "meme:item"})
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(
     *     min = 2,
     *     max = 30,
     *     minMessage = "Your title must be at least {{ limit }} characters long",
     *     maxMessage = "Your title cannot be longer than {{ limit }} characters"
     * )
     */
    private $title;

    /**
     * @ORM\Column(type="date")
     */
    private $created_at;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image;

    /**
     * @ORM\ManyToOne(targetEntity=User::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $created_by;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="meme", orphanRemoval=true)
     */
    private $comments;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $slug;

    /**
     * @ORM\OneToMany(targetEntity=Like::class, mappedBy="meme", orphanRemoval=true)
     */
    private $likes;

    /**
     * @ORM\OneToMany(targetEntity=Dislike::class, mappedBy="meme", orphanRemoval=true)
     */
    private $dislikes;



    public function __construct()
    {
        $this->comments = new ArrayCollection();
        $this->likes = new ArrayCollection();
        $this->dislikes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function setCreatedBy(?User $created_by): self
    {
        $this->created_by = $created_by;

        return $this;
    }

    public function getCreatedBy(): ?User
    {
        return $this->created_by;
    }

    /**
     * @return Collection|Like[]
     */
    public function getLikes(): Collection
    {
        return $this->likes;
    }

    public function addLike(Like $like): self
    {
        if (!$this->likes->contains($like)) {
            $this->likes[] = $like;
            $like->setMeme($this);
        }

        return $this;
    }

    public function removeLike(Like $like): self
    {
        if ($this->likes->removeElement($like)) {
            // set the owning side to null (unless already changed)
            if ($like->getMeme() === $this) {
                $like->setMeme(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Dislike[]
     */
    public function getDislikes(): Collection
    {
        return $this->dislikes;
    }

    public function addDislike(Dislike $dislike): self
    {
        if (!$this->dislikes->contains($dislike)) {
            $this->dislikes[] = $dislike;
            $dislike->setMeme($this);
        }

        return $this;
    }

    public function removeDislike(Dislike $dislike): self
    {
        if ($this->dislikes->removeElement($dislike)) {
            // set the owning side to null (unless already changed)
            if ($dislike->getMeme() === $this) {
                $dislike->setMeme(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setMeme($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getMeme() === $this) {
                $comment->setMeme(null);
            }
        }

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function computeSlug(SluggerInterface $slugger){
        if(!$this->slug || '-' === $this->slug){
            $this->slug = (string) $slugger->slug((string) $this)->lower();
        }
    }

    public function __toString(): string{
        return $this->title;
    }

    /**
     * @ORM\PrePersist
     */
    public function setCreatedAtValue(){
        $this->created_at = new \DateTime();
    }
}

templates/_header.html.twig
{% block javascripts %}
    <script src="{{ asset('js/searchMeme.js') }}" type="text/javascript" defer></script>
{% endblock %}
<header>
    <div class="search-bar">
        <form>
            <input placeholder="Search">
        </form>
    </div>
    {% if app.user %}
        <a class="login" href="{{ path('app_logout') }}">Logout</a>
    {% else %}
        <a class="login" href="{{ path('app_login') }}">Login</a>
    {% endif %}
</header>

templates/_memes.html.twig
{% block javascripts %}
    <script src="{{ asset('js/statistics.js') }}" type="text/javascript" defer></script>
{% endblock %}
<div class="memes">
    {% for meme in memes %}
        <div class="meme" id="{{ meme.getSlug }}">
            <a href="{{ path('meme', {'slug':meme.getSlug}) }}">
                <img src="uploads/{{ asset(meme.getImage) }}">
            </a>
            <div class="info">
                <h1> {{ meme.getTitle }} </h1>
                <div class="description">
                    <h2 id="email">{{ meme.createdBy.getEmail }}</h2>
                    <h2 id="date">{{ meme.getCreatedAt|date("Y-m-d") }}</h2>
                </div>
                <div class="social-section">
                    <i class="fas fa-thumbs-up">
                        <span>{{ meme.getLikes|length }}</span>
                    </i>
                    <a href="{{ path('meme', {'slug':meme.getSlug}) }}">Comments({{ meme.getComments|length }})</a>
                    <i class="fas fa-thumbs-down">
                        <span>{{ meme.getDislikes|length }}</span>
                    </i>
                </div>
            </div>
        </div>
    {% endfor %}
</div>

<template id="meme-template">
    <div class="meme" id="">
        <a href="">
            <img src="">
        </a>
        <div class="info">
            <h1> title </h1>
            <div class="description">
                <h2 id="email"> email </h2>
                <h2 id="date"> date </h2>
            </div>
            <div class="social-section">
                <i class="fas fa-thumbs-up">
                    <span> 0 </span>
                </i>
                <a href="">Comments(0)</a>
                <i class="fas fa-thumbs-down">
                    <span>0</span>
                </i>
            </div>
        </div>
    </div>
</template>

templates/_nav.html.twig
<nav>
    <img src="{{ asset('img/logo.svg') }}">
    <ul>
        <li>
            <i class="fas fa-home"></i>
            <a href="{{ path('home') }}" class="button">Home</a>
        </li>
        <li>
            <i class="fas fa-trophy"></i>
            <a href="{{ path('top10') }}" class="button">TOP10</a>
        </li>
        <li>
            <i class="fas fa-user"></i>
            <a href="{{ path('user') }}" class="button">Users</a>
        </li>
        <li>
            <i class="fas fa-plus-circle"></i>
            <a href="{{ path('add') }}" class="button">Add</a>
        </li>
    </ul>
</nav>